#index:
#    path: /
#    controller: App\Controller\DefaultController::index
cookiejar_folder_add:
    path: /add
    controller: App\Controller\FolderController::add

inscription:
    path: /inscription 
    controller: App\Controller\UserController::inscription

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin